export const ADDRESS_ACTIONS = {
    GET_ADDRESSES_REQUEST: "GET_ADDRESSES_REQUEST",
    GET_ADDRESSES_SUCCESS: "GET_ADDRESSES_SUCCESS",
    GET_ADDRESSES_FAILURE: "GET_ADDRESSES_FAILURE",
    ADD_ADDRESS_REQUEST: "ADD_ADDRESS_REQUEST",
    ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
    ADD_ADDRESS_FAILURE: "ADD_ADDRESS_FAILURE",
    SET_SELECTED_ADDRESS: "SET_SELECTED_ADDRESS",
    CLEAR_SELECTED_ADDRESS: "CLEAR_SELECTED_ADDRESS",
    CLEAR_ERROR: "CLEAR_ERROR",
};
