export const APP_SETTINGS_ACTIONS = {
    FETCH_SETTINGS_REQUEST: "FETCH_SETTINGS_REQUEST",
    FETCH_SETTINGS_SUCCESS: "FETCH_SETTINGS_SUCCESS",
    FETCH_SETTINGS_FAILURE: "FETCH_SETTINGS_FAILURE",
};

