export const AUTH_ACTIONS = {
    GET_USER_REQUEST: "GET_USER_REQUEST",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_FAILURE: "GET_USER_FAILURE",
    SET_SIGNIN_STATE: "SET_SIGNIN_STATE",
    CLEAR_SIGNIN_STATE: "CLEAR_SIGNIN_STATE",
    SET_SIGNUP_STATE: "SET_SIGNUP_STATE",
    CLEAR_SIGNUP_STATE: "CLEAR_SIGNUP_STATE",
    TOGGLE_IS_AUTHENTICATED: "TOGGLE_IS_AUTHENTICATED",
    SET_USER: "SET_USER",
};
